// @version 4.0.620
(function(o,p,h,C,J,y,K,s,u,na,R,D,v,L,ba,w,x,z,A,oa,S,T,E,ca,M,U,da,V,n){var N,O,W;function F(b,d,c,e){var f;(f=b.addEventListener)?f.call(b,d,c,v):b.attachEvent(e||"on"+d,c)}function r(b,d){return function(){b(d)}}function ea(b){function d(b){return"expires="+(new K(b)).toGMTString()+";"}var c="path=/;",e=q("cookieDomain");e&&(c+="domain="+e+";");return{B:function(f,e){N&&(h[T]=f+"="+e+";"+d(+new K+(b?6E10:6E4))+c)},s:function(b){if(N)return(h[T].match("(^|;)\\s*"+b+"=(.*?)(;|$)")||[])[2]||L},Z:function(b){h[T]=
b+"=;"+d(0)+c}}}function G(b){function d(){var b=f[E];b&&(f[E]=b[x](c)[0])}var c=":_GS_:",e;if(G.D)return G.D;var f=p.top;G.D=e={p:function(){d();f[E]=(f[E]||"")+c+[b,e.uid,e.h]}};try{var j=f[E]||"";if(-1!=j[V](c)){var l=j[x](c)[1][x](",");l[0]==b&&(e.uid=l[1]||"",e.h=l[2]||"")}d()}catch(k){e.p=function(){}}return e}function q(b,d){b=o[b];return b!==n?b:d}function pa(b,d){var c,e=p._gstc_lt,f=P(P(b).M),j=f.ta+(q("trackParams",D)?f.O:"")[z](/[?&]utm_[^=]*=[^&]*/g,"")+(q("trackHash")?f.sa:""),l=d!==
n?d:h.title,k=f.L,g=f.N,m=f.ua||"-";c=(c=p._gstc_s)&&e?e-c:n;var H;e&&(H=new K-e-q("TrackDelay"));return{ga:j,qa:l,$:k,ja:g,ka:m,ha:c,ra:H,ca:"file:"==f.N,ba:/fb_xd_(bust|fragment)/.test(f.M)}}function qa(){var b=q("referrer",h.referrer),d=h.domain,c=v;!b||/^(chrome|about|file):$/.test(b)?b="-":(d=P(b).L[V](d),c=0<=d&&8>=d,b=/^\[.*\]$/.test(b)?"-":b);return{t:+c,na:b}}function ra(b){var b=P(b).O,d,c,e,f;d=/[?&]([^=]+)=([^&]*)/g;c={};for(f=na;e=d.exec(b[z](/\+/g," "));c[f(e[1])]=f(e[2]));var j;if(b&&
(j=c.utm_campaign))return{U:j,V:c.utm_source,T:c.utm_medium,W:c.utm_term,S:c.utm_content}}function sa(b,d,c){var e=ea(1),f=G(b.c),j=e.s("gs_u")||f.uid,l=1,k=1,g=(j||"")[x](":"),m,H=D,h=0,X;!j||!j.match(/^[0-9\:]*$/)?(H=v,j=0|y.random()*ba):(j=g[0],2>g[A]&&(g[1]=2019,g[2]=4621),4>g[A]&&(g[3]=0),l=(g[1]-2019)/548+ +!!d,k=(g[2]-4621)/379+1,h=g[3]/1E3);e.B("gs_u",f.uid=[j,2019+548*l,4621+379*k,+new K].join(":"));d=e.s(O+b.c)||f.h;d!==L&&d!==n&&(X=d,e.Z(O+b.c));c&&(X=b.id);if((b=q("Visitor"))&&"object"==
typeof b){m=[];for(var o in b)b[ca](o)&&m.push(o+"="+("gravatar"==o?ta(b[o][z](/^\s+|\s+$/g,"")[S]()):b[o]));m=m.join("|")}return{id:+j,va:l,ma:k,fa:~~h,oa:H,ia:X,Y:m}}function Y(b){function d(b){var c=[],d;for(d in b)b[ca](d)&&b[d]!==n&&c.push((R||escape)(d)+"="+(R||escape)(b[d]));return c.join("&")}function c(){if(j)f[M](j);j=L;Z=(Z+1)%e[A];Y(b)}b.K===n&&(b.K=5);if(--b.K){var e=["data.gosquared.com/"],f=h[da]("head")[0],j=h[w]("script"),l=v,k=s(c,1E4),g=b.A+"?"+d(b.z);j.src="//"+e[Z]+g;j.onload=
j.onreadystatechange=function(c){c=this.readyState;if(!l&&(!c||c=="loaded"||c=="complete")){l=D;b.k&&b.k();if(j)f[M](j);j=L;u(k)}};f[U](j)}}function ua(){function b(b){for(var b=[b[z](/^./,function(b){return b[S]()}),"Webkit"+b,"Moz"+b,"O"+b,"ms"+b],c=0,d=b[A];d--;)e[b[d]]!==n&&(c=1);return c}var d="a"+(0|y.random()*ba),c=h[w]("div"),e=c.style,f=h[w]("canvas"),j,l=0;try{localStorage.setItem(d,d),localStorage.removeItem(d),l=1}catch(k){}var g=b("Perspective");if(g&&"webkitPerspective"in e){var m=h[w]("style");
m.textContent="@media (-webkit-transform-3d){#"+d+"{height:3px}}";h[da]("head")[0][U](m);c.id=d;h.body[U](c);g=3==c.offsetHeight;m.parentNode[M](m);c.parentNode[M](c)}return[+!(!f.getContext||!f.getContext("2d")),+!!function(){try{return p.WebGLRenderingContext&&(f.getContext("webgl")||f.getContext("experimental-webgl"))}catch(b){}}(),+("geolocation"in C),+!(!(j=p.history)||!j.pushState),+("WebSocket"in p||"MozWebSocket"in p),+!!h[w]("video").canPlayType,+!!h[w]("audio").canPlayType,+("placeholder"in
h[w]("input")),l,b("Transform"),+g,b("Transition"),+function(b,c){var d=c+b+"-";e.cssText=b+d+["webkit","moz","ms","o-"].join("-"+d)+c;return/grad/.test(e.background)}("background:","linear-gradient(top,red,red);"),b("AnimationName"),+!!p.Worker].join("")}function fa(){function b(b){return p["inner"+b]||e&&e[f="client"+b]||c&&c[f]}function d(b){return y.max(c[f="scroll"+b],e[f],c[f="offset"+b],e[f],c[f="client"+b],e[f])}var c=h.body,e=h.documentElement,f;return{R:b("Width"),P:b("Height"),r:d("Width"),
o:d("Height"),F:p.pageXOffset||c&&c.scrollLeft||e&&e.scrollLeft||0,G:p.pageYOffset||c&&c.scrollTop||e&&e.scrollTop||0}}function va(){var b={b:{f:0,d:0},m:"-",ea:(C.language||C.browserLanguage||"-")[S](),da:+C.javaEnabled(),X:h.characterSet||h.xa||"-",aa:function(b,d){var f,j,l,k,g;if(C&&(f=C.plugins)&&0<(j=f[A]))for(g=0;g<j;g++){if(-1<(k=f[g])[E][V](l=b+" "+d))return k.description[x](l+" "),k.description[x](l+" ")[1]}else if(f=p.ActiveXObject){try{if(k=(new f((l=b+d+".")+b+d)).GetVariable("$version"))return k=
k[x](" ")[1][x](","),k[0]+"."+k[1]+" r"+k[2]}catch(m){}for(g=13;--g;)try{if(k=new f(l+l+g),self.za=k&&k.wa,k)return g+".0"}catch(h){}}return"-"}("Shockwave","Flash")};if(J)b.b={f:J.width,d:J.height},b.m=J.colorDepth;else if(p.java)try{a=java.awt.Toolkit.getDefaultToolkit(),i=a.getScreenSize(),b.b={f:i.width,d:i.height}}catch(d){}return b}function wa(b){var d=ea();N?d.B(O+b.c,b.id):(d=G(b.c),d.h=b.id,d.p())}function ga(b){b.g=D;u(b.H)}function $(b){b.g=v;b.H=s(r(xa,b),36E6)}function xa(b){b.I=D;u(b.H)}
function ha(b){b.g||(ga(b),u(b.l),b.l=s(r($,b),6E4))}function ia(b,d){b[d.shift()].apply(b,d)}function Q(b,d,c){if(!b.I)if(b.id!==n){d!==n||(d=b.g?"focus":"blur");if(c===n)var e=fa(),c={vw:e.R,vh:e.P,dw:e.r,dh:e.o,st:e.G,sl:e.F};c=c||{};c.a=b.c;c.u=b.uid;c.i=b.id;c.e=d;c._=y.random();aa&&(b.v&&t)&&(b.v=v,c.o_si=t.C,c.o_vi=t.Q,c.o_ci=t.n);Y({A:"ping",k:function(){if(o.ps){u(b.j);if(!b.I)b.j=s(r(Q,b),17500+y.random()*5E3);delete o.ps}},z:c})}else{var f=arguments;s(function(){Q.apply(this,f)},5E3)}}
function ja(b,d){var c=pa(b,d),e=qa(),f=sa(this,!e.t,b!==n),j=va(),l=ra(b),k=fa(),g=q("errorCode");if(!c.ca&&!c.ba&&(!j.b.f||!j.b.d||!(10>j.b.f&&10>j.b.d))){var m=this,c={a:m.c,cs:j.X,cd:j.m,fl:j.aa,je:j.da,la:j.ea,sw:j.b.f,sh:j.b.d,dm:c.$,pa:c.ga,pt:c.qa,pr:c.ja,po:c.ka,pl:~~c.ha,tl:~~c.ra,ri:e.t,ru:e.na,ui:f.id,re:f.oa,vi:f.va,pv:f.ma,lv:f.fa,vw:k.R,vh:k.P,dw:k.r,dh:k.o,st:k.G,sl:k.F,tv:ya,un:q("UserName")||q("VisitorName"),pp:f.ia,cp:f.Y,ec:g,bs:ua()};m.uid=f.id;b===n&&(c.id=m.id);e.w&&(c.oe=e.w.ya,
c.ok=e.w.Aa);l&&(c.c_n=l.U,c.c_s=l.V,c.c_m=l.T,c.c_c=l.S,c.c_t=l.W);aa&&(t?(c.o_si=t.C,c.o_vi=t.Q,c.o_ci=t.n):m.v=D);e={A:"pv",z:c,k:function(){if(o.id!==n){m.id=o.id;delete o.id;m.j=s(r(Q,m),15E3);F(p,"beforeunload",r(wa,m))}}};u(m.j);Y(e);m.id!==n?b!==n&&(m.id=n):s(function(){F(h,"focus",r(ga,m),"focusin");F(h,"blur",r($,m),"focusout");F(h,"mousemove",r(ha,m));m.l=s(r($,m),6E4);F(h,"keydown",r(ha,m))},500)}}function ka(b){this.c=b;this.g=v}function la(b,d){d||(d=W);return o[d]?(ma(d),o[d]):o[d]=
new ka(b)}function ma(b){b||(b=W);o[b]&&u(o[b].J)}var ya="4.0",P=function(b){return function(d,c){d===n&&(d=location.href);b.href=d;return c={ta:b[oa][z](/^([^\/]|$)/,"/$1"),sa:b.hash[z](/^#$/,""),N:b.protocol[z](/^:$/,"")||location.protocol,L:b.hostname||location.hostname,M:b.href,O:b.search,ua:b.port}}}(h[w]("a"));O="gs_p_";N=!q("noCookies");W="DefaultTracker";var ta=function(b){function d(b,c){return((b>>1)+(c>>1)<<1)+(b&1)+(c&1)}for(var c=[],e=0;64>e;)c[e]=0|4294967296*y.abs(y.sin(++e));return function(f){for(var e,
l,k,g,m=[],f=unescape(R(f)),h=f[A],o=[e=1732584193,l=-271733879,~e,~l],n=0;n<=h;)m[n>>2]|=(f.charCodeAt(n)||128)<<8*(n++%4);m[f=(h+8>>6)*b+14]=8*h;for(n=0;n<f;n+=b){h=o;for(g=0;64>g;)h=[k=h[3],d(e=h[1],(k=d(d(h[0],[e&(l=h[2])|~e&k,k&e|~k&l,e^l^k,l^(e|~k)][h=g>>4]),d(c[g],m[[g,5*g+1,3*g+5,7*g][h]%b+n])))<<(h=[7,12,17,22,5,9,14,20,4,11,b,23,6,10,15,21][4*h+g++%4])|k>>>32-h),e,l];for(g=4;g;)o[--g]=d(o[g],h[g])}for(f="";32>g;)f+=(o[g>>3]>>4*(1^g++&7)&15).toString(b);return f}}(16),Z=0,aa=v,t,B=ka.prototype;
B.TrackView=ja;B.TrackEvent=function(b,d){if("string"==typeof d||"number"==typeof d)d={caption:d};d||(d={});d.gs_evt_name=b;Q(this,"event",d)};B.Cancel=function(){u(this.J)};o.Tracker=la;o.Cancel=ma;var I=la(q("acct")),B=o.TrackDelay=q("TrackDelay",50);I.J=s(function(){ja.call(I)},B);(function(){var b=p.olark;b&&b("api.boot.onIdentityReady",function(b,c,e){t={C:b,Q:c,n:e}});aa=!!b})();(B=q("load"))&&B(I);(function(){var b=q("q");if(b)for(var d=0;d<b[A];d+=1)ia(I,b[d]);o.q={push:function(b){ia(I,b)}}})()})(window.GoSquared||
(GoSquared={}),window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,decodeURIComponent,encodeURIComponent,1,0,null,2147483647,"createElement","split","replace","length","pathname","toLowerCase","cookie","name","hasOwnProperty","removeChild","appendChild","getElementsByTagName","indexOf");
